//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.27 at 01:23:19 PM GMT 
//


package org._3gpp.ftp.specs.archive._32_series._32;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org._3gpp.ftp.specs.archive._32_series._32 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org._3gpp.ftp.specs.archive._32_series._32
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MeasCollecFile }
     * 
     */
    public MeasCollecFile createMeasCollecFile() {
        return new MeasCollecFile();
    }

    /**
     * Create an instance of {@link MeasCollecFile.FileFooter }
     * 
     */
    public MeasCollecFile.FileFooter createMeasCollecFileFileFooter() {
        return new MeasCollecFile.FileFooter();
    }

    /**
     * Create an instance of {@link MeasCollecFile.MeasData }
     * 
     */
    public MeasCollecFile.MeasData createMeasCollecFileMeasData() {
        return new MeasCollecFile.MeasData();
    }

    /**
     * Create an instance of {@link MeasCollecFile.MeasData.MeasInfo }
     * 
     */
    public MeasCollecFile.MeasData.MeasInfo createMeasCollecFileMeasDataMeasInfo() {
        return new MeasCollecFile.MeasData.MeasInfo();
    }

    /**
     * Create an instance of {@link MeasCollecFile.MeasData.MeasInfo.MeasValue }
     * 
     */
    public MeasCollecFile.MeasData.MeasInfo.MeasValue createMeasCollecFileMeasDataMeasInfoMeasValue() {
        return new MeasCollecFile.MeasData.MeasInfo.MeasValue();
    }

    /**
     * Create an instance of {@link MeasCollecFile.FileHeader }
     * 
     */
    public MeasCollecFile.FileHeader createMeasCollecFileFileHeader() {
        return new MeasCollecFile.FileHeader();
    }

    /**
     * Create an instance of {@link MeasCollecFile.FileFooter.MeasCollec }
     * 
     */
    public MeasCollecFile.FileFooter.MeasCollec createMeasCollecFileFileFooterMeasCollec() {
        return new MeasCollecFile.FileFooter.MeasCollec();
    }

    /**
     * Create an instance of {@link MeasCollecFile.MeasData.ManagedElement }
     * 
     */
    public MeasCollecFile.MeasData.ManagedElement createMeasCollecFileMeasDataManagedElement() {
        return new MeasCollecFile.MeasData.ManagedElement();
    }

    /**
     * Create an instance of {@link MeasCollecFile.MeasData.MeasInfo.Job }
     * 
     */
    public MeasCollecFile.MeasData.MeasInfo.Job createMeasCollecFileMeasDataMeasInfoJob() {
        return new MeasCollecFile.MeasData.MeasInfo.Job();
    }

    /**
     * Create an instance of {@link MeasCollecFile.MeasData.MeasInfo.GranPeriod }
     * 
     */
    public MeasCollecFile.MeasData.MeasInfo.GranPeriod createMeasCollecFileMeasDataMeasInfoGranPeriod() {
        return new MeasCollecFile.MeasData.MeasInfo.GranPeriod();
    }

    /**
     * Create an instance of {@link MeasCollecFile.MeasData.MeasInfo.RepPeriod }
     * 
     */
    public MeasCollecFile.MeasData.MeasInfo.RepPeriod createMeasCollecFileMeasDataMeasInfoRepPeriod() {
        return new MeasCollecFile.MeasData.MeasInfo.RepPeriod();
    }

    /**
     * Create an instance of {@link MeasCollecFile.MeasData.MeasInfo.MeasType }
     * 
     */
    public MeasCollecFile.MeasData.MeasInfo.MeasType createMeasCollecFileMeasDataMeasInfoMeasType() {
        return new MeasCollecFile.MeasData.MeasInfo.MeasType();
    }

    /**
     * Create an instance of {@link MeasCollecFile.MeasData.MeasInfo.MeasValue.R }
     * 
     */
    public MeasCollecFile.MeasData.MeasInfo.MeasValue.R createMeasCollecFileMeasDataMeasInfoMeasValueR() {
        return new MeasCollecFile.MeasData.MeasInfo.MeasValue.R();
    }

    /**
     * Create an instance of {@link MeasCollecFile.FileHeader.FileSender }
     * 
     */
    public MeasCollecFile.FileHeader.FileSender createMeasCollecFileFileHeaderFileSender() {
        return new MeasCollecFile.FileHeader.FileSender();
    }

    /**
     * Create an instance of {@link MeasCollecFile.FileHeader.MeasCollec }
     * 
     */
    public MeasCollecFile.FileHeader.MeasCollec createMeasCollecFileFileHeaderMeasCollec() {
        return new MeasCollecFile.FileHeader.MeasCollec();
    }

}

