//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.27 at 01:23:19 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.3gpp.org/ftp/specs/archive/32_series/32.435#measCollec", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org._3gpp.ftp.specs.archive._32_series._32;

